outputFolder: "./output/fit"
minGundamVersion: 1.9.0

fitterEngineConfig:

  minimizerConfig:
    type: "RootMinimizer"

  likelihoodInterfaceConfig:

    dataSetList: "./example/advanced/inputs/datasets/config.yaml"

    plotGeneratorConfig: "./example/advanced/inputs/plots/config.yaml"

    propagatorConfig:
      sampleSetConfig: "./example/advanced/inputs/samples/config.yaml"
      parametersManagerConfig: "./example/advanced/inputs/parameters/config.yaml"
