outputFolder: "./output/fit"
minGundamVersion: 1.9.0

fitterEngineConfig:

  minimizerConfig:
    type: "RootMinimizer"

  likelihoodInterfaceConfig:

    dataSetList: "./super_advanced_gundam_example/inputs/datasets/config.yaml"

    plotGeneratorConfig: "./super_advanced_gundam_example/inputs/plots/config.yaml"

    propagatorConfig:
      sampleSetConfig: "./super_advanced_gundam_example/inputs/samples/config.yaml"
      parametersManagerConfig: "./super_advanced_gundam_example/inputs/parameters/config.yaml"
